[package]
name = "utils"
version = "1.0.0"
description = "Utilities functions"
authors = ["sodiumlabs"]
edition = "2021"
license = "Apache-2.0"

[lib]
name = "utils"
path = "src/lib.rs"

[dependencies]
url = "2.5.4"
