[package]
name = "database"
version = "1.0.0"
description = "The PostgreSQL database lib"
authors = ["sodiumlabs"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
diesel = { version = "2.2.8", features = ["postgres", "r2d2"] }

[lib]
name = "database"
path = "src/lib.rs"